---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: glusterfs-daemonset
spec:
  template:
    metadata:
      name: glusterfs
      labels:
        app: glusterfs
    spec:
      hostNetwork: true
#     nodeSelector:
      containers:
      - name: glusterfs
        image: glusterfs:3.7.18
        imagePullPolicy: IfNotPresent
        #command: [ "sh", "-c", "echo 'running since '`date +'%r'`; while true; do sleep 600; done"]
        args: ["/build/entrypoint.sh"]
        volumeMounts:
        - name: devtree
          mountPath: "/dev"
        - name: glusterfs-etc
          mountPath: "/etc/glusterfs"
        - name: glusterfs-logs
          mountPath: "/var/log/glusterfs"
        - name: glusterfs-config
          mountPath: "/var/lib/glusterd"
        - name: glusterfs
          mountPath: "/glusterfs"
        securityContext:
          privileged: true
      volumes:
      - name: devtree
        hostPath:
          path: "/dev"
      - name: glusterfs-etc
        hostPath:
          path: "/etc/glusterfs"
      - name: glusterfs-logs
        hostPath:
          path: "/var/log/glusterfs"
      - name: glusterfs-config
        hostPath:
          path: "/var/lib/glusterd"
      - name: glusterfs
        hostPath:
          path: "/glusterfs"
