#cloud-config

coreos:
  units:
    - name: pxe-installd.service
      command: start
      content: |
        [Unit]
        Description=ipxe-installd
        After=network-online.target download-cloud-config.service
        Requires=network-online.target download-cloud-config.service 
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/bin/bash -c "wget -c -P /root http://iPXE_Server_IP/bin/grandsys-coreos-install && chmod +x /root/grandsys-coreos-install"
        ExecStart=/root/grandsys-coreos-install -d /dev/sda -c /root/coreos-cloud-config.yml -b http://iPXE_Server_IP/images/coreos/amd64-usr -V VersionVar

    - name: download-cloud-config.service
      command: start
      content: |
        [Unit]
        Requires=network-online.target
        After=network-online.target
        Description=download-cloud-config.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/wget http://iPXE_Server_IP/cloud-configs/coreos-cloud-config.yml -O /root/coreos-cloud-config.yml

    - name: ipxe-cleand.service
      command: start
      content: |
        [Unit]
        Description=pxe-cleand
        Requires=network-online.target ipxe-installd.service
        After=network-online.target ipxe-installd.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/bash -c 'wget -O - http://iPXE_Server_IP/bin/ipxe-cleand.sh | bash -'
